pipeline/LogAnalysis.py
Signed-off-by: AndyBoWu <bwu2sfu@gmail.com>
=> support fatal query in log

pipeline/deploy.sh
this is not necessary anymore
the hardcoded harmony-s3 profile have been removed
=> remove -p support in deploy.sh

pipeline/common.sh, pipeline/go.sh, pipeline/run_benchmark.sh
Add a call to r53update.py to update hostzone automatically after launch of testnet.
=> Support user specified prikey

configs/benchmark-drum.json, configs/launch-drum.json, pipeline/go.sh
=> [profile] add drum profile

configs/benchmark-drum.json, configs/launch-drum.json, pipeline/common.sh, pipeline/common_test.sh, pipeline/run_benchmark.sh
reserve more FN account index.
=> Reserved more for FN

configs/benchmark-drum.json, configs/launch-drum.json
add SIN/FRA in drum testnet launch to provide better network coverage
=> [drum] add FN 192/193

pipeline/dl-soldier-logs.sh
=> [log] create the db.tgz with the new name of db files

configs/benchmark-drum.json, configs/launch-drum.json
=> [drum] adjust the profile for better launch

configs/launch-mainrc2.json
=> [mainrc2] use on-demand instances

pipeline/go.sh, pipeline/run_benchmark.sh
This is for DNS-based sync peer lookup.
=> Give rpczone, if defined, to Harmony binary

configs/launch-r3.json
=> [r3] replace fra with cmh for r3 profile

pipeline/node_ssh.sh
=> [node_ssh] support -p profile option

pipeline/aws-instances.sh
=> [aws] support disable detailed cloudwatch monitoring

pipeline/common.sh, pipeline/go.sh, pipeline/run_benchmark.sh
=> Pass benchmark.network_type option to node binary

pipeline/dl-soldier-logs.sh
=> [log] use rsync to download the logs from soldiers

pipeline/go.sh
=> [bootnode] support selectively launch bootnode

pipeline/go.sh
=> [rpc] reduce number of nodes to 5 for each rpc endpoint

configs/benchmark-puzzle.json, configs/launch-puzzle.json
=> created and updated puzzle profile

pipeline/common_opts.sh, pipeline/sync_logs.sh
https://github.com/harmony-one/experiment-deploy/issues/80
=> [whomi] check WHOAMI variable setting

pipeline/bootnode.sh
SSIA.  For harmony-one/harmony-ops#113.
=> Run bootnode with 4k file descriptors

pipeline/restart_node.sh
public rpc is enabled by default
=> [restart] support -P to disable public RPC

pipeline/restart_node.sh
=> [restart] support terraform node in restart/rolling update

pipeline/log.sh, pipeline/node_ssh.sh
=> [node_ssh] fix mac compatibility issue

tf/aws.1/main.tf, tf/aws.1/variables.tf
1. change the termination behaviour from `termination` to `stop`
2. change the spot type request from `one time` to `persistant`
=> change termination behaviour and spot type

pipeline/node_ssh.sh, pipeline/run_on_shard.sh, pipeline/util.sh
=> [node_ssh] support ssh to gcp nodes

pipeline/node_ssh.sh, pipeline/util.sh
previous implementation of running many host commands concurrently
had caused issue like the following. I found the issue while running
run_on_shard.sh command on mainnet.
"host: isc_socketmgr_create: unexpected error"
So, I changed the implementation to only run 'host' command once per IP.
Tried it to run on mainnet shards, and the run_on_shard.sh command succeeded
without errors now.
=> [node_ssh] fix the bug of concurrent host command

tf/gcp/files/harmony.service
=> [tf] expose rpc port for gcp node

tf/aws.1/main.tf, tf/aws.1/variables.tf
1. extend ebs size from 150 to 200
2. resolved a conflict in main.tf
=> Pr tf ebs 200

configs/benchmark-t2.json, configs/launch-t2.json, pipeline/go.sh
recreate t2 profile based on its previous template
=> make changes to t2 profile for testnet launching

tf/gcp/go.sh, tf/gcp/main.tf, tf/gcp/variables.tf
=> [tf] add shard name to gcp node

configs/benchmark-mkeys.json, configs/launch-mkeys.json
network for multiple BLS keys testing
=> profile for launching a network for mkeys testing

configs/benchmark-mkeys.json, configs/launch-mkeys.json
=> [config] testent config update for mkey

configs/benchmark-mkeys.json, configs/launch-mkeys.json
=> [mkeys] 2*30 configuration

configs/benchmark-mkeys.json, configs/launch-mkeys.json, configs/userdata-soldier-http-static.sh, pipeline/common.sh, pipeline/deploy.sh
=> [profile] test out static build binary

configs/userdata-soldier-http.sh, pipeline/go.sh
=> deploy: fix userdata and r53 duplicated records issue

pipeline/restart_node.sh
force kill the harmony process since the current script can not kill the harmony process any more
=> force kill the harmony process 

pipeline/restart_node.sh
=> [restart] no need to update .so files

tf/do/go.sh
=> generated new ssh key, need to set location of the pem file

configs/benchmark-os.json, configs/launch-os.json
notes:
* 4 shards in total
* 25 by us, 25 open to the public after staking epoch
* need to create endpoints
* update watchdog
* update network dashboard
* staking explorer
=> new OSTN profile

tf/do/files/reboot.sh, tf/do/files/userdata.sh, tf/do/go.sh, tf/do/main.tf
first part of integration
* created a userdata.sh file to download, install and config node_exporter
* refactored main.tf
* disabled selinux on dropet
* reboot the instance to make sure selinux can be disabled
=> Pr integrate node exporter into tf

pipeline/fund.py
Adds a funding script that uses the profile to automatically fund given accounts without the use of an endpoint.
=> [pipeline] Add funding script

tf/do/go.sh, tf/do/main.tf, tf/do/variables.tf
* add DNS support for outbound rules
* fix IP variable typo
* move harmony.service to its proper place
=> Pr node exporter bugs fix

pipeline/restart_node.sh, pipeline/run_on_shard.sh
* Add confirmation to restart a shard
* Remove profile from env vars for running on shard
and add confirmation for cmd ran on shard
```
[ec2-user@ip-172-31-37-52 pipeline]$ ./run_on_shard.sh -p os -T 0 'tac ../tmp_log/*/zerolog*.log | grep -m 1 HOORAY'
profile: os
execute: 'tac ../tmp_log/*/zerolog*.log | grep -m 1 HOORAY'
[Y]/n > Y
run_on_shard.sh: using timestamp 20200228.034942 (from logs/os -> /home/ec2-user/experiment-deploy/pipeline/logs/20200228.034942)
run_on_shard.sh: using outdir logs/os/run_on_shard/2020-03-04T04:59:55Z.AwhpZg
{"level":"info","port":"9000","ip":"34.228.217.167","myEpoch":42,"myBlock":3173,"myViewID":3173,"phase":0,"mode":"Normal","blockNum":3172,"epochNum":42,"ViewId":3172,"blockHash":"0xcd070746fc944634c63b00b770f57f350ccdb1dae7f6dbe3fa97f348b0d3af8b","index":0 …
```
=> [pipeline] Add confirmation to pipeline scripts

configs/benchmark-leo.json, configs/launch-leo.json
=> [leo] update profile with multi-key and static binary

pipeline/go.sh, tf/aws.1/go.sh
=> add multikey uptime update support

configs/benchmark-os.json
=> add mkeys support for OSTN config

configs/benchmark-ps.json, configs/benchmark-stn.json, configs/launch-ps.json, configs/launch-stn.json
=> PSTN and STN config changes

configs/aws-explorer.json, pipeline/go.sh
=> [explorer] use different security group for explorer node

pipeline/consolidate.py, pipeline/consolidate_test_funds.json, pipeline/fund.py
* Make fund.py check for profile before continuing
* Add funds consolidation script
* Add TestingKey consolidation config
=> [pipeline] Add fund consolidation script and update fund script

configs/benchmark-stn.json, configs/launch-stn.json
=> Update config for STN to make smaller

pipeline/run_benchmark.sh
=> launch explorer node with archival mode

configs/benchmark-os.json
=> [ostn] set rpcnode to 5 for p2

pipeline/fund.py
=> [fund.py] add profile in the name of json files

configs/benchmark-os.json
=> [p2] 3s commit delay for harmony nodes

pipeline/fund.py, pipeline/fund.sh
* Update nonce setting to account for different balances
The script was tested on STN.
=> [pipeline] Update fund.py and fund.sh to pull from spreadsheet

pipeline/util.sh
=> [ssh] OSTN relaunched with testnet key

tf/aws.1/go.sh, tf/aws.1/main.tf
=> [tf] use proxy mode for private key

pipeline/node_ssh.sh
=> [node_ssh.sh] change default location of keys

pipeline/run_benchmark.sh
=> [mkey] create multi-keys.csv file

configs/benchmark-andy.json, configs/launch-andy.json
transient network, won't keep it running overnight usually.
=> test network for Jenkins automation

pipeline/bls.py, pipeline/fund.py
This script will help find the missing BLS keys of harmony nodes in a network. It will also report the intended distribution of BLS keys.
Example commands (on STN):
```
$ python3 bls.py ref --shard 0
Machine 0
e7f54994bc5c02edeeb178ce2d34db276a893bab5c59ac3d7eb9f077c893f9e31171de6236ba0e21be415d8631e45b91
a2b1b534c94bf19a92551f1d32d62b802be6996458f65b0baeb081c9972b34d72310e675fc7797b9c860d8cc223cee8f
d13e1d260791bda54201d77ff44bab65e628e82a8d96e3804bb2852dc1459ecb59cd788c04a3f1fd3e2c6a5fc3242b84
Machine 1
e212c4c5cd8e078aedd34c300ae500c5bd5fd036231d1c9dcc8400337919a59ebd47523faa209fc0d873ead492621f88
68b97efd30c635af5053e4fddf88f2c00f437ed3d24d88f4b369ec6761a3b315a9e01c80116bef5c854583784a7eec89
ff6eae041955e6ce5f6e9ece59c7aa3f5d0c66ea8023cbf4afa1354565424d353718f1281d2b758ee3aff0b769e0c28 …
```
=> Add pipeline script to get BLS key information of a network.

pipeline/go.sh
=> [go.sh] auto restart shards after launch the network

pipeline/bootnode.sh, pipeline/dl-soldier-logs.sh
=> [ssh] unify the default location of keys

pipeline/fund.py, pipeline/fund.sh
Needed so we can automatically fund new accounts that are added to the sheet.
=> [pipeline] Log funded accounts with fund.py and prevent double fund

pipeline/go.sh
=> [restart] add -U option to support upgrade

pipeline/go.sh
=> [go.sh] send leaders.json to explorer automatically

pipeline/restart_node.sh
Signed-off-by: Daniel <daniel@harmony.one>
=> add -d to clean .dht during node restart

pipeline/update_watchdog.sh
[watchdog] If update nodedb fails, exit & don't push
[watchdog] Take additional confirmation on the push
=> [watchdog] Add option to skip update

pipeline/restart_node.sh
=> [restart_node] support static for legacy node by default

pipeline/update_watchdog.sh
[watchdog] Copy files if update script fails for any reason
[watchdog] Additional prints for visibility & updated error prints to be more visible
=> [watchdog] Add way to bypass nodedb script update & just copy files

configs/benchmark-stn.json, configs/launch-stn.json
=> [stn] updated profile using od c5.large instances

pipeline/go.sh
=> [go.sh] fixed a typo of the scripe name

pipeline/restart_node.sh
=> [restart_node] add -X to clean harmony_db

pipeline/common.sh
=> [misc] fix a typo in common.sh

pipeline/update_watchdog.sh
=> fix a missing fi in update_watchdog.sh

tools/install-node_exporter.sh
=> [node_exporter] add a node_exporter installation script

pipeline/go.sh
Signed-off-by: Daniel <daniel@harmony.one>
=> output time expense of network restart

tools/Makefile, tools/enable-systemd-service.sh, tools/harmony.service.template, tools/install-node_exporter.sh
support various network
support validator/explorer nodes
tested on stn validator/explorer nodes
=> [tools] convert legacy node to use systemd.service

tools/enable-systemd-service.sh
=> [tools] use one-liner example for systemd service

pipeline/restart_watchdog.sh, pipeline/update_nodedb.sh
[watchdog] New script to just restart Watchdog services
=> [nodedb] Add ability to copy init files to nodedb

configs/benchmark-stn.json, pipeline/common.sh, pipeline/hard-reset.sh, pipeline/restart_node.sh
=> [hardreset] script to automate the hardreset

configs/benchmark-stn.json, pipeline/common.sh, pipeline/dl-soldier-logs.sh, pipeline/go.sh, pipeline/hard-reset.sh
=> [hard-reset] add capture validator info and pagerduty support

pipeline/restart_node.sh
add a func to clean up explorer db if it is an exp node, no extra argument needed.
=> add a feature to clean up explorer db

pipeline/restart_node.sh
=> [restart] support upgrade of testnet node using node.sh

pipeline/hard-reset.sh
do funding after reset explorer and dashboard
=> [hardreset] separate funding step

pipeline/hard-reset.sh
=> [hardreset] restart explorer backend using new script

pipeline/hard-reset.sh
=> [hardreset] fix ssh command to restart backend of explorer

tools/enable-systemd-service.sh
remove explorer storage during restart
=> modify systemd script usage

pipeline/hard-reset.sh
soft_reset will only restart the shard w/o clean up db
=> [hardreset] add a soft_reset action support

pipeline/hard-reset.sh
=> [hardreset] forget to add fund command in check

tf/aws.1/main.tf
=> [tf] delete volume after termination

pipeline/merge_node.sh
TODO: create a node merge plan
TODO: update nodedb script, now one node can have up to 10 keys
=> [merge] merge nodes into one node

pipeline/run_on_shard.sh
=> [run_on_shard] remove the legacy -t option

pipeline/dl-soldier-logs.sh, pipeline/fund.py
* [pipeline] update log saving script for new nodes
=> [pipeline] update funding script to be more defensive

configs/benchmark-s3.json, pipeline/restart_node.sh
=> [restart_node.sh] run node.sh w/o root permission

tools/enable-systemd-service.sh, tools/harmony.service.template
=> [systemd] update systemd conversion script

configs/benchmark-stn.json
=> update stn profile

pipeline/hard-reset.sh
=> [hard-reset] fix unbound option variable

configs/benchmark-dryrun.json, configs/launch-dryrun.json, pipeline/common.sh
=> [dryrun] update profile

ansible/playbooks/sysctl-setup.yml
create an ansible playbook to run sysctl setup on any node.
=> [#286]add ansible playbook to run sysctl setup

ansible/playbooks/install-node-exporter.yml, ansible/playbooks/roles/node_exporter/files/node_exporter.service, ansible/playbooks/roles/node_exporter/tasks/main.yml, ansible/playbooks/roles/node_exporter/vars/1.0-Amazon.yml, ansible/playbooks/roles/node_exporter/vars/Azure-CentOS.yml, ansible/playbooks/roles/node_exporter/vars/Google-CentOS.yml
add an ansible role to install node_exporter systemd service
=> [#292]add ansible role to install node_exporter

tools/Makefile, tools/install-db-snapshot.sh, tools/mainnet.snapshot.json, tools/test.only.json
=> [snapshot] init version of snapshot script

configs/benchmark-dryrun.json, configs/launch-dryrun.json, configs/userdata-systemd-static-dryrun.sh
=> [dryrun] typo in the dns zone

pipeline/merge_node.sh
=> [merge_node] support merge node by index

tools/install-db-snapshot.sh, tools/mainnet.snapshot.json, tools/test.only.json
=> [snapsho] support cleanup

pipeline/restart_node.sh
=> [restart_node.sh] upgrade node.sh w/ harmony binary

configs/benchmark-dryrun.json, pipeline/hard-reset.sh
=> add dryrun network support in hard-reset

pipeline/restart_node.sh
=> [restart_node] improve the probe_node_type func

pipeline/hard-reset.sh
=> [hard-reset] do upgrade during soft_reset

tools/Makefile, tools/install-db-snapshot.sh, tools/snapshots/main.all.0501.json, tools/snapshots/main.all.0504.json, tools/snapshots/main.s0.0501.json, tools/snapshots/main.s1.0504.json, tools/snapshots/main.s2.0505.json, tools/snapshots/main.s3.0505.json, tools/snapshots/upload.sh
=> [snapshot] replace only specified db snapshot

tools/install-node.sh, tools/launch-node.sh
This closes #313 
Note that the install script can also act as an upgrade script for our existing systemd setup.
I tested on PSTN, it works.
=> Harmony node internal daemon

pipeline/restart_node.sh
=> [restart] do not wait if -t 0

configs/benchmark-lrtn.json, configs/launch-lrtn.json, configs/userdata-systemd-static-lrtn-exp.sh, configs/userdata-systemd-static-lrtn.sh
Have to use 1 region, could not get sufficient sigs in 4 regions, idk why.
=> [config] fix lrtn config

tools/Makefile, tools/check_lsof.sh
=> [check_lsof] add a script to check open files

pipeline/rollback.sh
=> [rollback] init version of rollback script

pipeline/r53update.py
=> [r53] set TTL to 300 for DNS records

tf/aws.1/files/harmony-mk.service, tf/aws.1/go.sh
=> [tf] fix newmk for aws node

ansible/playbooks/users.yml, ansible/scripts/users.sh
=> [ansible] remove sudo users if they are removed

pipeline/hard-reset.sh, pipeline/restart_node.sh
=> [hard-reset] add lrtn support

pipeline/download-logs.sh
=> fix download log for single ip

ansible/playbooks/upgrade-node.yml, ansible/playbooks/vars/1.0-Amazon.yml, ansible/playbooks/vars/Azure-CentOS.yml, ansible/playbooks/vars/Google-CentOS.yml, ansible/playbooks/vars/VirtualBox-Ubuntu.yml, ansible/scripts/canary.sh
=> [ansible] add node upgrade playbook

tools/snapshot/README.md, tools/snapshot/snapshot.py
Needed as fresh installs will have to add RSA keys initially
=> [snapshot] Add init option and update README.md

pipeline/rolling_restart_shard.sh
=> [rolling upgrade] adjust the default options

tools/snapshot/README.md, tools/snapshot/requirements.txt, tools/snapshot/snapshot.py, tools/snapshot/testnet_config.json
* Update README.md
* Update requirements.txt
* Update testnet_config.json
* Includes bug fixes found when setting up mainnet snapshot
=> [snapshot] Add pagerduty integration & bug fix

ansible/playbooks/upgrade-node.yml
=> [ansible] print out upgraded version after node upgrade

tf/azure.tn/main.tf, tf/azure.tn/output.tf, tf/azure.tn/variables.tf
=> [tf] add azure testnet script

ansible/playbooks/check-bingo.yml, ansible/playbooks/cleanup.yml, ansible/playbooks/roles/node/tasks/main.yml, ansible/playbooks/roles/node/templates/harmony.service.j2, ansible/playbooks/roles/node/vars/Azure-CentOS.yml, ansible/playbooks/vars/4.2.amazon-Amazon.yml, experiment/genbls/Makefile, experiment/genbls/main.go, go.mod, go_executable_build.sh, testnet/stn/launch.sh
=> [genbls] program to generate list of blskeys

pipeline/merge_node.sh
This is the change being made for merge nodes bls keys (https://github.com/harmony-one/nodedb/issues/20).
1. Set timeout to 0
2. Update BLSKeyIndex regex
=> Update for merge node task

ansible/playbooks/install-filebeat.yml, ansible/playbooks/roles/filebeat/files/elastic.repo, ansible/playbooks/roles/filebeat/tasks/main.yml, ansible/playbooks/roles/filebeat/templates/filebeat.yml.j2, ansible/scripts/install_filebeat.sh
add install filebeat on harmony node script
=> [ansible]add_install_filebeat_script

ansible/playbooks/restart-node.yml, ansible/scripts/upgrade-stn.sh
=> [ansible] a playbook to restart node

pipeline/merge_node.sh, pipeline/restart_watchdog.sh
`restart_watchdog.sh` service params add `testnet` option
=> [watchdog]update_option_add_testnet
